name = "MyProject"
uuid = "4dd9378c-b5f7-4bb8-a10d-c7d4e9302bda"
authors = ["Charles' MBP <cs9303@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
